# [START cloudrun_rails_cloudbuild]
steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ["-c", "docker build -f Dockerfile.run --build-arg SECRET_KEY_BASE=$$RAILS_KEY -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} . "]
    secretEnv: ["RAILS_KEY"]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
    - -c
    - |
      gcloud run deploy ${_SERVICE_NAME} --image gcr.io/${PROJECT_ID}/${_SERVICE_NAME} \
      --update-env-vars=RAILS_MASTER_KEY=$$RAILS_KEY \
      --update-env-vars=SECRET_KEY_BASE=$$RAILS_KEY \
      --update-env-vars=DB_HOST=$$DB_HOST \
      --update-env-vars=DB_PORT=$$DB_PORT \
      --update-env-vars=DB_NAME=$$DB_NAME \
      --update-env-vars=DB_USER=$$DB_USER \
      --update-env-vars=DB_PASS=$$DB_PASS \
      --update-env-vars=RAILS_SERVE_STATIC_FILES=true \
      --update-env-vars=GOOGLE_PROJECT_ID=${PROJECT_ID} \
      --update-env-vars=GOOGLE_CLOUD_BUCKET_NAME=$$BUCKET_NAME \
      --update-env-vars=GOOGLE_SERVICE_ACCOUNT_JSON=$$SERVICE_ACCOUNT_JSON \
      --region asia-northeast1 \
      --allow-unauthenticated
    secretEnv: ["RAILS_KEY", "DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASS", "BUCKET_NAME", "SERVICE_ACCOUNT_JSON"]

substitutions:
  _SERVICE_NAME: rails-cloud-run-chat
  _SECRET_NAME: RAILS_KEY

availableSecrets:
  secretManager:
  - versionName: projects/156178245176/secrets/${_SECRET_NAME}/versions/latest
    env: RAILS_KEY
  - versionName: projects/156178245176/secrets/CHAT_DB_HOST/versions/latest
    env: DB_HOST
  - versionName: projects/156178245176/secrets/CHAT_DB_PORT/versions/latest
    env: DB_PORT
  - versionName: projects/156178245176/secrets/CHAT_DB_NAME/versions/latest
    env: DB_NAME
  - versionName: projects/156178245176/secrets/CHAT_DB_USER/versions/latest
    env: DB_USER
  - versionName: projects/156178245176/secrets/CHAT_DB_PASS/versions/latest
    env: DB_PASS
  - versionName: projects/156178245176/secrets/CHAT_BUCKET_NAME/versions/latest
    env: BUCKET_NAME
  - versionName: projects/156178245176/secrets/GOOGLE_SERVICE_ACCOUNT_JSON/versions/latest
    env: SERVICE_ACCOUNT_JSON

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"

options:
  logging: CLOUD_LOGGING_ONLY
# [END cloudrun_rails_cloudbuild]
